tsconfig.json
=> fix: ignore typecheck for playground

README.md, src/cli.ts, src/context.ts, src/renderer/header.ts, src/renderer/usage.ts, src/renderer/validation.ts, src/types.ts, src/utils.ts
=> fix: default type

README.md, playground/README.md, playground/bun/index.ts, src/cli.test.ts, src/cli.ts, src/types.ts, src/utils.ts
=> fix: sub command type frustration

src/renderer/usage.ts
=> fix: resolve description

playground/i18n/index.js, src/cli.test.ts, src/cli.ts
=> fix: sub-commands registration bug

README.md, eslint.config.ts, knip.config.ts, playground/custom-usage/index.js, playground/deno/locales/en-US.json, playground/deno/locales/ja-JP.json, playground/i18n/index.js, playground/i18n/locales/en-US.json, playground/i18n/locales/ja-JP.json, src/cli.test.ts, src/cli.ts, src/constants.ts, src/context.test.ts, src/context.ts, src/renderer.test.ts, src/renderer/usage.ts, src/types.ts, src/utils.ts
=> breaking: i18n resource flatten

README.md, docs/guide/advanced/documentation-generation.md, docs/guide/essentials/auto-usage-generation.md, docs/guide/essentials/declarative-configuration.md, docs/guide/essentials/getting-started.md, docs/guide/essentials/lazy-async.md, package.json, playground/auto-usage/index.js, playground/bun/index.ts, playground/composable/index.js, playground/custom-usage/index.js, playground/declarative/index.js, playground/deno/main.ts, playground/docs-gen/index.js, playground/i18n/index.js, playground/lazy-async/index.js, playground/type-safe/index.ts, pnpm-lock.yaml, src/cli.test.ts, src/constants.ts, src/context.test.ts, src/context.ts, src/renderer.test.ts, src/renderer/usage.ts, src/types.ts, tsconfig.json
=> breaking: drop `CommandUsage`, use args-tokens option description and hoist examples to `Command`

docs/guide/advanced/documentation-generation.md, eslint.config.ts, package.json, playground/docs-gen/index.js, src/__snapshots__/generator.test.ts.snap, src/generator.test.ts, src/generator.ts, test/fixtures/register.ts, test/fixtures/show.ts, tsdown.config.ts
=> feat: support usage generation for `generate` function

jsr.json
=> fix: export generator for jsr

src/context.ts
=> fix: wrong dynamic import json resource

src/types.ts
=> fix: wrong type resolve on deno

package.json, src/cli.ts, src/constants.ts, src/generator.ts, src/index.ts, src/renderer/header.ts, src/renderer/index.ts, src/renderer/usage.ts, src/renderer/validation.ts, src/types.ts, typedoc.config.mjs
=> feat: export constant and tweak docs

docs/guide/advanced/translation-adapter.md, src/translation.test.ts, src/translation.ts
=> feat: support simple interpolation

src/cli.test.ts, src/cli.ts, src/context.test.ts, src/context.ts, src/renderer.test.ts, src/types.ts
=> feat: support raw args on `CommandContext._`

src/index.ts
=> feat: export `parseArgs` and `resolveArgs`

src/__snapshots__/cli.test.ts.snap, src/cli.test.ts, src/cli.ts, src/context.test.ts, src/context.ts, src/renderer.test.ts, src/types.ts, test/__snapshots__/issue.test.ts.snap
=> feat: export tokens for `CommandContext`

src/cli.test.ts, src/cli.ts
=> fix: allow positional arguments for entry command only

src/cli.test.ts, src/cli.ts
=> fix: not found command, when default command has name and no sub-command

docs/guide/essentials/declarative-configuration.md, package.json, pnpm-lock.yaml, src/cli.test.ts, src/cli.ts
=> feat: support short option grouping

src/__snapshots__/cli.test.ts.snap, src/cli.test.ts
=> feat: support enum option via `args-tokens`

jsr.json, package.json, src/context.ts, tsdown.config.ts
=> feat: export context

package.json, pnpm-lock.yaml, src/types.test-d.ts
resolve #103 
related fixed PR: https://github.com/kazupon/args-tokens/pull/81
=> fix: readonly string array error for enum option

src/__snapshots__/cli.test.ts.snap, src/__snapshots__/generator.test.ts.snap, src/__snapshots__/renderer.test.ts.snap, src/constants.ts, src/locales/en-US.json, src/locales/ja-JP.json, src/renderer.test.ts, src/renderer/usage.ts, src/types.ts
=> feat: show option value on help usage

src/cli.ts, src/constants.ts, src/context.test.ts, src/context.ts
=> fix: command name resolving correctly

README.md
fix just a tiny English grammar mistake
Thank you for featuring my son!
=> docs: sitemcp a->an

packages/gunshi/src/cli.test.ts, packages/gunshi/src/cli/core.ts, packages/gunshi/src/types.ts
=> feat: support sub commands object style
